# Generated by Django 2.1.5 on 2019-01-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='Art',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='Video',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
